get "/students", to: "students#index"
get "/students/:id", to: "students#show"
post "/students", to: "students#create"
put "/students/:id", to: "students#update"
delete "/students/:id", to: "students#delete"
